//! MKV-corpus regression suite.
//!
//! Reads `tests/data/regression-manifest.toml`, streams each track's
//! pre-extracted `.eac3` through a single stateful `PcmDecoder`, compares
//! the resulting PCM against the FFmpeg and Cavern oracle dumps, and:
//!
//! - witness tracks must decode every frame and match each oracle within
//!   a 1e-3 absolute tolerance; failures fail the test.
//! - failing tracks are exercised in report-only mode; the result is
//!   written to `target/eac3-regression-report.txt` for the developer to
//!   inspect, never gating the test.
//!
//! When the corpus directory or any oracle dump is missing the test prints
//! a `[skip]` line and returns success, so CI without the NAS still passes.
//!
//! Layout required by this test (regenerated by
//! `scripts/run-eac3-regression.sh`):
//!
//! ```text
//! <workspace>/dumps/eac3-regression/
//!     <track-id>/track.eac3
//!     ffmpeg-pcm/<track-id>.f32
//!     cavern-pcm/<track-id>.f32
//! ```

use std::fs::{self, File};
use std::io::{BufReader, BufWriter, Read, Write};
use std::path::{Path, PathBuf};

use eac3::{BedChannel, CorePcmFrame, Extractor, PcmDecoder};

const CHANNEL_COUNT: usize = 6;
const TOLERANCE: f32 = 1.0e-3;
const MANIFEST_PATH: &str = "tests/data/regression-manifest.toml";

#[derive(Debug)]
struct TrackEntry {
    id: String,
    role: Role,
    #[allow(dead_code)]
    source: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Role {
    Witness,
    Failing,
}

#[derive(Debug)]
struct Comparison {
    aligned_samples: usize,
    max_abs_diff: f32,
    first_div_idx: Option<usize>,
    per_channel_rmse: [f64; CHANNEL_COUNT],
}

#[test]
fn mkv_corpus_regression() {
    let workspace = match find_workspace_root() {
        Some(p) => p,
        None => {
            println!("[skip] could not locate workspace root from CARGO_MANIFEST_DIR");
            return;
        }
    };

    let manifest_path = Path::new(env!("CARGO_MANIFEST_DIR")).join(MANIFEST_PATH);
    let tracks = match load_manifest(&manifest_path) {
        Ok(t) => t,
        Err(e) => panic!("could not read manifest {}: {e}", manifest_path.display()),
    };

    let corpus_root = workspace.join("dumps/eac3-regression");
    if !corpus_root.exists() {
        println!(
            "[skip] corpus directory missing: {}",
            corpus_root.display()
        );
        return;
    }

    let report_path = Path::new(env!("CARGO_TARGET_TMPDIR"))
        .parent()
        .map(Path::to_path_buf)
        .unwrap_or_else(|| PathBuf::from("target"))
        .join("eac3-regression-report.txt");
    if let Some(parent) = report_path.parent() {
        let _ = fs::create_dir_all(parent);
    }
    let mut report = BufWriter::new(
        File::create(&report_path).expect("failed to create regression report"),
    );

    let mut failed_witnesses: Vec<String> = Vec::new();

    for track in &tracks {
        let track_dir = corpus_root.join(&track.id);
        let eac3_path = track_dir.join("track.eac3");
        let ffmpeg_path = corpus_root
            .join("ffmpeg-pcm")
            .join(format!("{}.f32", track.id));
        let cavern_path = corpus_root
            .join("cavern-pcm")
            .join(format!("{}.f32", track.id));

        if !eac3_path.exists() {
            let msg = format!("[skip] {} missing track.eac3 ({})", track.id, eac3_path.display());
            println!("{msg}");
            writeln!(report, "{msg}").ok();
            continue;
        }

        let outcome = run_track(&eac3_path, &ffmpeg_path, &cavern_path);
        match outcome {
            Ok(summary) => {
                println!("{}", summary.console_line(&track.id, track.role));
                writeln!(report, "{}", summary.report_block(&track.id, track.role)).ok();
                if track.role == Role::Witness && !summary.passes() {
                    failed_witnesses.push(track.id.clone());
                }
            }
            Err(e) => {
                let msg = format!("[error] {}: {e}", track.id);
                println!("{msg}");
                writeln!(report, "{msg}").ok();
                if track.role == Role::Witness {
                    failed_witnesses.push(track.id.clone());
                }
            }
        }
    }

    drop(report);
    println!("regression report: {}", report_path.display());

    if !failed_witnesses.is_empty() {
        panic!(
            "witness track(s) regressed: {} (see {})",
            failed_witnesses.join(", "),
            report_path.display()
        );
    }
}

#[derive(Debug)]
struct TrackSummary {
    frame_count: u64,
    decode_errors: u64,
    pcm_max_abs: f32,
    vs_ffmpeg: Option<Comparison>,
    vs_cavern: Option<Comparison>,
}

impl TrackSummary {
    fn passes(&self) -> bool {
        if self.decode_errors > 0 {
            return false;
        }
        if !self.pcm_max_abs.is_finite() || self.pcm_max_abs > 1.5 {
            return false;
        }
        let ok = |cmp: &Option<Comparison>| match cmp {
            None => true, // missing oracle = treat as best-effort
            Some(c) => c.max_abs_diff <= TOLERANCE,
        };
        ok(&self.vs_ffmpeg) && ok(&self.vs_cavern)
    }

    fn console_line(&self, id: &str, role: Role) -> String {
        let role_s = match role {
            Role::Witness => "witness",
            Role::Failing => "failing",
        };
        let ff = self
            .vs_ffmpeg
            .as_ref()
            .map(|c| format!("ffmpeg max={:.2e} first_div={:?}", c.max_abs_diff, c.first_div_idx))
            .unwrap_or_else(|| "ffmpeg=skipped".into());
        let cv = self
            .vs_cavern
            .as_ref()
            .map(|c| format!("cavern max={:.2e} first_div={:?}", c.max_abs_diff, c.first_div_idx))
            .unwrap_or_else(|| "cavern=skipped".into());
        format!(
            "[{role_s}] {id} frames={} errors={} max_abs={:.3} | {ff} | {cv}",
            self.frame_count, self.decode_errors, self.pcm_max_abs
        )
    }

    fn report_block(&self, id: &str, role: Role) -> String {
        let mut s = String::new();
        s.push_str(&format!("=== {id} ({:?}) ===\n", role));
        s.push_str(&format!(
            "frames={} decode_errors={} pcm_max_abs={:.4}\n",
            self.frame_count, self.decode_errors, self.pcm_max_abs
        ));
        for (label, cmp) in [
            ("vs ffmpeg", &self.vs_ffmpeg),
            ("vs cavern", &self.vs_cavern),
        ] {
            match cmp {
                Some(c) => {
                    s.push_str(&format!(
                        "{label}: aligned={} max_abs={:.3e} first_div_idx={:?}\n",
                        c.aligned_samples, c.max_abs_diff, c.first_div_idx
                    ));
                    s.push_str("  rmse:");
                    for v in &c.per_channel_rmse {
                        s.push_str(&format!(" {v:.3e}"));
                    }
                    s.push('\n');
                }
                None => s.push_str(&format!("{label}: skipped (oracle missing)\n")),
            }
        }
        s
    }
}

fn run_track(
    eac3_path: &Path,
    ffmpeg_path: &Path,
    cavern_path: &Path,
) -> Result<TrackSummary, String> {
    let harletty_pcm = decode_harletty(eac3_path).map_err(|e| format!("decode {eac3_path:?}: {e}"))?;

    let frame_count = harletty_pcm.frame_count;
    let decode_errors = harletty_pcm.decode_errors;
    let pcm_max_abs = harletty_pcm.max_abs;

    let pcm = harletty_pcm.samples;

    let vs_ffmpeg = if ffmpeg_path.exists() {
        let ff = load_f32(ffmpeg_path).map_err(|e| format!("load ffmpeg pcm: {e}"))?;
        Some(compare(&pcm, &ff))
    } else {
        None
    };
    let vs_cavern = if cavern_path.exists() {
        let cv = load_f32(cavern_path).map_err(|e| format!("load cavern pcm: {e}"))?;
        Some(compare(&pcm, &cv))
    } else {
        None
    };

    Ok(TrackSummary {
        frame_count,
        decode_errors,
        pcm_max_abs,
        vs_ffmpeg,
        vs_cavern,
    })
}

struct HarlettyDecoded {
    samples: Vec<f32>,
    frame_count: u64,
    decode_errors: u64,
    max_abs: f32,
}

fn decode_harletty(eac3_path: &Path) -> std::io::Result<HarlettyDecoded> {
    let file = File::open(eac3_path)?;
    let mut reader = BufReader::with_capacity(64 * 1024, file);
    let mut buf = [0u8; 64 * 1024];

    let mut decoder = PcmDecoder::new();
    let mut extractor = Extractor::default();
    let mut samples: Vec<f32> = Vec::new();
    let mut frame_count = 0u64;
    let mut decode_errors = 0u64;
    let mut max_abs = 0.0_f32;
    let mut last_core_samples: usize = 1536;

    loop {
        let n = reader.read(&mut buf)?;
        let eof = n == 0;
        if !eof {
            extractor.push_bytes(&buf[..n]);
        }
        loop {
            let frame = match extractor.next_frame() {
                Ok(Some(f)) => f,
                Ok(None) => break,
                Err(_) => {
                    decode_errors += 1;
                    samples.extend(std::iter::repeat_n(
                        0.0_f32,
                        last_core_samples * CHANNEL_COUNT,
                    ));
                    break;
                }
            };
            match decoder.push_access_unit(frame.as_bytes()) {
                Ok(result) => {
                    frame_count += 1;
                    last_core_samples = result.pcm.samples_per_channel().max(1);
                    if let Some(m) = append_core_interleaved(&result.pcm, &mut samples) {
                        if m > max_abs {
                            max_abs = m;
                        }
                    }
                }
                Err(_) => {
                    decode_errors += 1;
                    samples.extend(std::iter::repeat_n(
                        0.0_f32,
                        last_core_samples * CHANNEL_COUNT,
                    ));
                }
            }
        }
        if eof {
            break;
        }
    }

    Ok(HarlettyDecoded {
        samples,
        frame_count,
        decode_errors,
        max_abs,
    })
}

fn append_core_interleaved(frame: &CorePcmFrame, out: &mut Vec<f32>) -> Option<f32> {
    let nsamples = frame.samples_per_channel();
    if nsamples == 0 {
        return None;
    }
    let order = [
        BedChannel::FrontLeft,
        BedChannel::FrontRight,
        BedChannel::Center,
        BedChannel::LowFrequencyEffects,
        BedChannel::SurroundLeft,
        BedChannel::SurroundRight,
    ];
    let mut slots: [Option<&[f32]>; CHANNEL_COUNT] = [None; CHANNEL_COUNT];
    for (idx, ch) in frame.fullband_channel_order.iter().enumerate() {
        if let Some(pos) = order.iter().position(|c| c == ch) {
            slots[pos] = frame.fullband_channels.get(idx).map(Vec::as_slice);
        }
    }
    if let Some(lfe) = frame.lfe_channel.as_deref() {
        slots[3] = Some(lfe);
    }
    let zero = vec![0.0f32; nsamples];
    let resolved: [&[f32]; CHANNEL_COUNT] = [
        slots[0].unwrap_or(&zero),
        slots[1].unwrap_or(&zero),
        slots[2].unwrap_or(&zero),
        slots[3].unwrap_or(&zero),
        slots[4].unwrap_or(&zero),
        slots[5].unwrap_or(&zero),
    ];
    let mut local_max = 0.0_f32;
    out.reserve(nsamples * CHANNEL_COUNT);
    for i in 0..nsamples {
        for ch in &resolved {
            let v = ch.get(i).copied().unwrap_or(0.0);
            if v.abs() > local_max {
                local_max = v.abs();
            }
            out.push(v);
        }
    }
    Some(local_max)
}

fn load_f32(path: &Path) -> std::io::Result<Vec<f32>> {
    let file = File::open(path)?;
    let len = file.metadata()?.len() as usize;
    if !len.is_multiple_of(4) {
        return Err(std::io::Error::other(format!(
            "{}: size {} not a multiple of 4 bytes",
            path.display(),
            len
        )));
    }
    let mut reader = BufReader::with_capacity(1 << 20, file);
    let nsamples = len / 4;
    let mut out = Vec::with_capacity(nsamples);
    let mut buf = [0u8; 4];
    for _ in 0..nsamples {
        reader.read_exact(&mut buf)?;
        out.push(f32::from_le_bytes(buf));
    }
    Ok(out)
}

fn compare(a: &[f32], b: &[f32]) -> Comparison {
    let aligned_samples = a.len().min(b.len()) / CHANNEL_COUNT * CHANNEL_COUNT;
    let mut sum_sq = [0.0_f64; CHANNEL_COUNT];
    let mut max_abs_diff = 0.0_f32;
    let mut first_div_idx: Option<usize> = None;
    for i in 0..aligned_samples {
        let d = a[i] - b[i];
        let abs = d.abs();
        let ch = i % CHANNEL_COUNT;
        sum_sq[ch] += (d as f64) * (d as f64);
        if abs > max_abs_diff {
            max_abs_diff = abs;
        }
        if first_div_idx.is_none() && abs > TOLERANCE {
            first_div_idx = Some(i);
        }
    }
    let nframes = (aligned_samples / CHANNEL_COUNT).max(1) as f64;
    let mut rmse = [0.0_f64; CHANNEL_COUNT];
    for ch in 0..CHANNEL_COUNT {
        rmse[ch] = (sum_sq[ch] / nframes).sqrt();
    }
    Comparison {
        aligned_samples,
        max_abs_diff,
        first_div_idx,
        per_channel_rmse: rmse,
    }
}

fn find_workspace_root() -> Option<PathBuf> {
    let here = Path::new(env!("CARGO_MANIFEST_DIR")); // .../harletty-bridge/eac3
    here.parent()?.parent().map(Path::to_path_buf)
}

fn load_manifest(path: &Path) -> std::io::Result<Vec<TrackEntry>> {
    let text = fs::read_to_string(path)?;
    let mut tracks: Vec<TrackEntry> = Vec::new();
    let mut current: Option<(Option<String>, Option<String>, Option<String>)> = None;
    for raw in text.lines() {
        let line = raw.split('#').next().unwrap_or("").trim();
        if line.is_empty() {
            continue;
        }
        if line == "[[track]]" {
            if let Some(t) = current.take() {
                push_track(&mut tracks, t)?;
            }
            current = Some((None, None, None));
            continue;
        }
        let entry = current
            .as_mut()
            .ok_or_else(|| std::io::Error::other(format!("stray field outside [[track]]: {line}")))?;
        let (key, value) = parse_kv(line)
            .ok_or_else(|| std::io::Error::other(format!("malformed manifest line: {line}")))?;
        match key.as_str() {
            "id" => entry.0 = Some(value),
            "role" => entry.1 = Some(value),
            "source" => entry.2 = Some(value),
            other => {
                return Err(std::io::Error::other(format!(
                    "unknown manifest key: {other}"
                )));
            }
        }
    }
    if let Some(t) = current.take() {
        push_track(&mut tracks, t)?;
    }
    Ok(tracks)
}

fn push_track(
    tracks: &mut Vec<TrackEntry>,
    t: (Option<String>, Option<String>, Option<String>),
) -> std::io::Result<()> {
    let id = t
        .0
        .ok_or_else(|| std::io::Error::other("[[track]] missing id"))?;
    let role_s = t
        .1
        .ok_or_else(|| std::io::Error::other("[[track]] missing role"))?;
    let source = t
        .2
        .ok_or_else(|| std::io::Error::other("[[track]] missing source"))?;
    let role = match role_s.as_str() {
        "witness" => Role::Witness,
        "failing" => Role::Failing,
        other => {
            return Err(std::io::Error::other(format!("unknown role: {other}")));
        }
    };
    tracks.push(TrackEntry { id, role, source });
    Ok(())
}

fn parse_kv(line: &str) -> Option<(String, String)> {
    let eq = line.find('=')?;
    let key = line[..eq].trim().to_string();
    let raw_value = line[eq + 1..].trim();
    let value = if raw_value.starts_with('"') && raw_value.ends_with('"') && raw_value.len() >= 2 {
        raw_value[1..raw_value.len() - 1].to_string()
    } else {
        raw_value.to_string()
    };
    Some((key, value))
}
