//! MKV-corpus regression suite.
//!
//! Reads `tests/data/regression-manifest.toml`, streams each track's
//! pre-extracted `.eac3` through a single stateful `PcmDecoder`, compares
//! the resulting PCM against the FFmpeg and Cavern oracle dumps, and:
//!
//! - witness tracks must decode every frame and match each oracle within
//!   a 1e-3 absolute tolerance; failures fail the test.
//! - failing tracks are exercised in report-only mode; the result is
//!   written to `target/eac3-regression-report.txt` for the developer to
//!   inspect, never gating the test.
//!
//! When the corpus directory or any oracle dump is missing the test prints
//! a `[skip]` line and returns success, so CI without the NAS still passes.
//!
//! Layout required by this test (regenerated by
//! `scripts/run-eac3-regression.sh`):
//!
//! ```text
//! <workspace>/dumps/eac3-regression/
//!     <track-id>/track.eac3
//!     ffmpeg-pcm/<track-id>.f32
//!     cavern-pcm/<track-id>.f32
//! ```

use std::fs::{self, File};
use std::io::{BufReader, BufWriter, Read, Write};
use std::path::{Path, PathBuf};

use eac3::{BedChannel, CorePcmFrame, Extractor, PcmDecoder};

const CHANNEL_COUNT: usize = 6;
const TOLERANCE: f32 = 1.0e-3;
const MANIFEST_PATH: &str = "tests/data/regression-manifest.toml";

#[derive(Debug)]
struct TrackEntry {
    id: String,
    role: Role,
    #[allow(dead_code)]
    source: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Role {
    Witness,
    Failing,
}

#[derive(Debug)]
struct Comparison {
    aligned_samples: usize,
    max_abs_diff: f32,
    first_div_idx: Option<usize>,
    per_channel_rmse: [f64; CHANNEL_COUNT],
}

#[test]
fn mkv_corpus_regression() {
    let workspace = match find_workspace_root() {
        Some(p) => p,
        None => {
            println!("[skip] could not locate workspace root from CARGO_MANIFEST_DIR");
            return;
        }
    };

    let manifest_path = Path::new(env!("CARGO_MANIFEST_DIR")).join(MANIFEST_PATH);
    let tracks = match load_manifest(&manifest_path) {
        Ok(t) => t,
        Err(e) => panic!("could not read manifest {}: {e}", manifest_path.display()),
    };

    let corpus_root = workspace.join("dumps/eac3-regression");
    if !corpus_root.exists() {
        println!(
            "[skip] corpus directory missing: {}",
            corpus_root.display()
        );
        return;
    }

    let report_path = Path::new(env!("CARGO_TARGET_TMPDIR"))
        .parent()
        .map(Path::to_path_buf)
        .unwrap_or_else(|| PathBuf::from("target"))
        .join("eac3-regression-report.txt");
    if let Some(parent) = report_path.parent() {
        let _ = fs::create_dir_all(parent);
    }
    let mut report = BufWriter::new(
        File::create(&report_path).expect("failed to create regression report"),
    );

    let mut failed_witnesses: Vec<String> = Vec::new();

    for track in &tracks {
        let track_dir = corpus_root.join(&track.id);
        let eac3_path = track_dir.join("track.eac3");
        let ffmpeg_path = corpus_root
            .join("ffmpeg-pcm")
            .join(format!("{}.f32", track.id));
        let cavern_path = corpus_root
            .join("cavern-pcm")
            .join(format!("{}.f32", track.id));

        if !eac3_path.exists() {
            let msg = format!("[skip] {} missing track.eac3 ({})", track.id, eac3_path.display());
            println!("{msg}");
            writeln!(report, "{msg}").ok();
            continue;
        }

        let outcome = run_track(&eac3_path, &ffmpeg_path, &cavern_path);
        match outcome {
            Ok(summary) => {
                println!("{}", summary.console_line(&track.id, track.role));
                writeln!(report, "{}", summary.report_block(&track.id, track.role)).ok();
                if track.role == Role::Witness && !summary.passes() {
                    failed_witnesses.push(track.id.clone());
                }
            }
            Err(e) => {
                let msg = format!("[error] {}: {e}", track.id);
                println!("{msg}");
                writeln!(report, "{msg}").ok();
                if track.role == Role::Witness {
                    failed_witnesses.push(track.id.clone());
                }
            }
        }
    }

    drop(report);
    println!("regression report: {}", report_path.display());

    if !failed_witnesses.is_empty() {
        panic!(
            "witness track(s) regressed: {} (see {})",
            failed_witnesses.join(", "),
            report_path.display()
        );
    }
}

#[derive(Debug)]
struct TrackSummary {
    frame_count: u64,
    decode_errors: u64,
    pcm_max_abs: f32,
    vs_ffmpeg: Option<Comparison>,
    vs_cavern: Option<Comparison>,
}

impl TrackSummary {
    fn passes(&self) -> bool {
        if self.decode_errors > 0 {
            return false;
        }
        // E-AC-3 PCM at full bitstream scale (no dialnorm, no DRC, no
        // limiter) can legitimately peak well above 1.0 — observed 2.23
        // on Dune Part Two's main track. FFmpeg with `-drc_scale 0` and
        // Cavern (raw decoder, pre-Listener normalizer) peak similarly
        // (1.80 and 1.89 respectively). 4.0 is a sanity ceiling for
        // catastrophic over-range / NaN-like garbage, not a content cap.
        if !self.pcm_max_abs.is_finite() || self.pcm_max_abs > 4.0 {
            return false;
        }
        // Use per-channel RMSE rather than max_abs_diff for the strict
        // gate: max_abs_diff can spike on isolated samples (especially
        // on coupled front channels) due to f32 IMDCT precision
        // differences between decoders, even when the average error is
        // tiny. RMSE captures the systematic divergence we actually care
        // about for regression detection.
        const WITNESS_RMSE_LIMIT: f64 = 5.0e-3;
        let ok = |cmp: &Option<Comparison>| match cmp {
            None => true, // missing oracle = treat as best-effort
            Some(c) => c.per_channel_rmse.iter().all(|r| *r <= WITNESS_RMSE_LIMIT),
        };
        ok(&self.vs_ffmpeg) && ok(&self.vs_cavern)
    }

    fn console_line(&self, id: &str, role: Role) -> String {
        let role_s = match role {
            Role::Witness => "witness",
            Role::Failing => "failing",
        };
        let ff = self
            .vs_ffmpeg
            .as_ref()
            .map(|c| format!("ffmpeg max={:.2e} first_div={:?}", c.max_abs_diff, c.first_div_idx))
            .unwrap_or_else(|| "ffmpeg=skipped".into());
        let cv = self
            .vs_cavern
            .as_ref()
            .map(|c| format!("cavern max={:.2e} first_div={:?}", c.max_abs_diff, c.first_div_idx))
            .unwrap_or_else(|| "cavern=skipped".into());
        format!(
            "[{role_s}] {id} frames={} errors={} max_abs={:.3} | {ff} | {cv}",
            self.frame_count, self.decode_errors, self.pcm_max_abs
        )
    }

    fn report_block(&self, id: &str, role: Role) -> String {
        let mut s = String::new();
        s.push_str(&format!("=== {id} ({:?}) ===\n", role));
        s.push_str(&format!(
            "frames={} decode_errors={} pcm_max_abs={:.4}\n",
            self.frame_count, self.decode_errors, self.pcm_max_abs
        ));
        for (label, cmp) in [
            ("vs ffmpeg", &self.vs_ffmpeg),
            ("vs cavern", &self.vs_cavern),
        ] {
            match cmp {
                Some(c) => {
                    s.push_str(&format!(
                        "{label}: aligned={} max_abs={:.3e} first_div_idx={:?}\n",
                        c.aligned_samples, c.max_abs_diff, c.first_div_idx
                    ));
                    s.push_str("  rmse:");
                    for v in &c.per_channel_rmse {
                        s.push_str(&format!(" {v:.3e}"));
                    }
                    s.push('\n');
                }
                None => s.push_str(&format!("{label}: skipped (oracle missing)\n")),
            }
        }
        s
    }
}

fn run_track(
    eac3_path: &Path,
    ffmpeg_path: &Path,
    cavern_path: &Path,
) -> Result<TrackSummary, String> {
    // Stream harletty PCM to a temp file so the comparison phase can
    // mmap/stream-read it without materialising 11.5 GB in RAM (the full
    // 2 h Dune track would OOM-kill a 60 GB box if loaded whole alongside
    // the FFmpeg + Cavern oracles).
    let tmp_path = std::env::temp_dir().join(format!(
        "eac3-mkv-test-{}.f32",
        eac3_path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("unknown")
    ));
    let decoded = decode_harletty_to_file(eac3_path, &tmp_path)
        .map_err(|e| format!("decode {eac3_path:?}: {e}"))?;
    let result = (|| -> Result<TrackSummary, String> {
        let vs_ffmpeg = if ffmpeg_path.exists() {
            Some(stream_compare(&tmp_path, ffmpeg_path).map_err(|e| format!("vs ffmpeg: {e}"))?)
        } else {
            None
        };
        let vs_cavern = if cavern_path.exists() {
            Some(stream_compare(&tmp_path, cavern_path).map_err(|e| format!("vs cavern: {e}"))?)
        } else {
            None
        };
        Ok(TrackSummary {
            frame_count: decoded.frame_count,
            decode_errors: decoded.decode_errors,
            pcm_max_abs: decoded.max_abs,
            vs_ffmpeg,
            vs_cavern,
        })
    })();
    let _ = fs::remove_file(&tmp_path);
    result
}

struct HarlettyDecoded {
    frame_count: u64,
    decode_errors: u64,
    max_abs: f32,
}

fn decode_harletty_to_file(eac3_path: &Path, out_path: &Path) -> std::io::Result<HarlettyDecoded> {
    let file = File::open(eac3_path)?;
    let mut reader = BufReader::with_capacity(64 * 1024, file);
    let mut buf = [0u8; 64 * 1024];

    let out_file = File::create(out_path)?;
    let mut writer = BufWriter::with_capacity(1 << 20, out_file);

    let mut decoder = PcmDecoder::new();
    let mut extractor = Extractor::default();
    let mut frame_count = 0u64;
    let mut decode_errors = 0u64;
    let mut max_abs = 0.0_f32;
    let mut last_core_samples: usize = 1536;

    loop {
        let n = reader.read(&mut buf)?;
        let eof = n == 0;
        if !eof {
            extractor.push_bytes(&buf[..n]);
        }
        loop {
            let frame = match extractor.next_frame() {
                Ok(Some(f)) => f,
                Ok(None) => break,
                Err(_) => {
                    decode_errors += 1;
                    write_silence(&mut writer, last_core_samples)?;
                    break;
                }
            };
            match decoder.push_access_unit(frame.as_bytes()) {
                Ok(result) => {
                    frame_count += 1;
                    last_core_samples = result.pcm.samples_per_channel().max(1);
                    let local_max = write_core_interleaved(&mut writer, &result.pcm)?;
                    if local_max > max_abs {
                        max_abs = local_max;
                    }
                }
                Err(_) => {
                    decode_errors += 1;
                    write_silence(&mut writer, last_core_samples)?;
                }
            }
        }
        if eof {
            break;
        }
    }
    writer.flush()?;

    Ok(HarlettyDecoded {
        frame_count,
        decode_errors,
        max_abs,
    })
}

fn write_core_interleaved(
    writer: &mut BufWriter<File>,
    frame: &CorePcmFrame,
) -> std::io::Result<f32> {
    let nsamples = frame.samples_per_channel();
    if nsamples == 0 {
        return Ok(0.0);
    }
    let order = [
        BedChannel::FrontLeft,
        BedChannel::FrontRight,
        BedChannel::Center,
        BedChannel::LowFrequencyEffects,
        BedChannel::SurroundLeft,
        BedChannel::SurroundRight,
    ];
    let mut slots: [Option<&[f32]>; CHANNEL_COUNT] = [None; CHANNEL_COUNT];
    for (idx, ch) in frame.fullband_channel_order.iter().enumerate() {
        if let Some(pos) = order.iter().position(|c| c == ch) {
            slots[pos] = frame.fullband_channels.get(idx).map(Vec::as_slice);
        }
    }
    if let Some(lfe) = frame.lfe_channel.as_deref() {
        slots[3] = Some(lfe);
    }
    let zero = vec![0.0f32; nsamples];
    let resolved: [&[f32]; CHANNEL_COUNT] = [
        slots[0].unwrap_or(&zero),
        slots[1].unwrap_or(&zero),
        slots[2].unwrap_or(&zero),
        slots[3].unwrap_or(&zero),
        slots[4].unwrap_or(&zero),
        slots[5].unwrap_or(&zero),
    ];
    let mut local_max = 0.0_f32;
    for i in 0..nsamples {
        for ch in &resolved {
            let v = ch.get(i).copied().unwrap_or(0.0);
            if v.abs() > local_max {
                local_max = v.abs();
            }
            writer.write_all(&v.to_le_bytes())?;
        }
    }
    Ok(local_max)
}

fn write_silence(writer: &mut BufWriter<File>, samples_per_channel: usize) -> std::io::Result<()> {
    let zero = 0.0f32.to_le_bytes();
    for _ in 0..(samples_per_channel * CHANNEL_COUNT) {
        writer.write_all(&zero)?;
    }
    Ok(())
}

fn stream_compare(a_path: &Path, b_path: &Path) -> std::io::Result<Comparison> {
    let a_file = File::open(a_path)?;
    let b_file = File::open(b_path)?;
    let a_total = a_file.metadata()?.len() as usize / 4;
    let b_total = b_file.metadata()?.len() as usize / 4;
    let aligned_samples = a_total.min(b_total) / CHANNEL_COUNT * CHANNEL_COUNT;

    let mut a_reader = BufReader::with_capacity(1 << 20, a_file);
    let mut b_reader = BufReader::with_capacity(1 << 20, b_file);
    const CHUNK: usize = 16_384 * CHANNEL_COUNT;
    let mut a_buf = vec![0u8; CHUNK * 4];
    let mut b_buf = vec![0u8; CHUNK * 4];

    let mut sum_sq = [0.0_f64; CHANNEL_COUNT];
    let mut max_abs_diff = 0.0_f32;
    let mut first_div_idx: Option<usize> = None;
    let mut consumed: usize = 0;

    while consumed < aligned_samples {
        let remaining = aligned_samples - consumed;
        let this_chunk = remaining.min(CHUNK);
        let bytes = this_chunk * 4;
        a_reader.read_exact(&mut a_buf[..bytes])?;
        b_reader.read_exact(&mut b_buf[..bytes])?;
        for i in 0..this_chunk {
            let off = i * 4;
            let av = f32::from_le_bytes([
                a_buf[off],
                a_buf[off + 1],
                a_buf[off + 2],
                a_buf[off + 3],
            ]);
            let bv = f32::from_le_bytes([
                b_buf[off],
                b_buf[off + 1],
                b_buf[off + 2],
                b_buf[off + 3],
            ]);
            let d = av - bv;
            let abs = d.abs();
            let ch = i % CHANNEL_COUNT;
            sum_sq[ch] += (d as f64) * (d as f64);
            if abs > max_abs_diff {
                max_abs_diff = abs;
            }
            if first_div_idx.is_none() && abs > TOLERANCE {
                first_div_idx = Some(consumed + i);
            }
        }
        consumed += this_chunk;
    }

    let nframes = (aligned_samples / CHANNEL_COUNT).max(1) as f64;
    let mut rmse = [0.0_f64; CHANNEL_COUNT];
    for ch in 0..CHANNEL_COUNT {
        rmse[ch] = (sum_sq[ch] / nframes).sqrt();
    }
    Ok(Comparison {
        aligned_samples,
        max_abs_diff,
        first_div_idx,
        per_channel_rmse: rmse,
    })
}

fn find_workspace_root() -> Option<PathBuf> {
    let here = Path::new(env!("CARGO_MANIFEST_DIR")); // .../harletty-bridge/eac3
    here.parent()?.parent().map(Path::to_path_buf)
}

fn load_manifest(path: &Path) -> std::io::Result<Vec<TrackEntry>> {
    let text = fs::read_to_string(path)?;
    let mut tracks: Vec<TrackEntry> = Vec::new();
    let mut current: Option<(Option<String>, Option<String>, Option<String>)> = None;
    for raw in text.lines() {
        let line = raw.split('#').next().unwrap_or("").trim();
        if line.is_empty() {
            continue;
        }
        if line == "[[track]]" {
            if let Some(t) = current.take() {
                push_track(&mut tracks, t)?;
            }
            current = Some((None, None, None));
            continue;
        }
        let entry = current
            .as_mut()
            .ok_or_else(|| std::io::Error::other(format!("stray field outside [[track]]: {line}")))?;
        let (key, value) = parse_kv(line)
            .ok_or_else(|| std::io::Error::other(format!("malformed manifest line: {line}")))?;
        match key.as_str() {
            "id" => entry.0 = Some(value),
            "role" => entry.1 = Some(value),
            "source" => entry.2 = Some(value),
            other => {
                return Err(std::io::Error::other(format!(
                    "unknown manifest key: {other}"
                )));
            }
        }
    }
    if let Some(t) = current.take() {
        push_track(&mut tracks, t)?;
    }
    Ok(tracks)
}

fn push_track(
    tracks: &mut Vec<TrackEntry>,
    t: (Option<String>, Option<String>, Option<String>),
) -> std::io::Result<()> {
    let id = t
        .0
        .ok_or_else(|| std::io::Error::other("[[track]] missing id"))?;
    let role_s = t
        .1
        .ok_or_else(|| std::io::Error::other("[[track]] missing role"))?;
    let source = t
        .2
        .ok_or_else(|| std::io::Error::other("[[track]] missing source"))?;
    let role = match role_s.as_str() {
        "witness" => Role::Witness,
        "failing" => Role::Failing,
        other => {
            return Err(std::io::Error::other(format!("unknown role: {other}")));
        }
    };
    tracks.push(TrackEntry { id, role, source });
    Ok(())
}

fn parse_kv(line: &str) -> Option<(String, String)> {
    let eq = line.find('=')?;
    let key = line[..eq].trim().to_string();
    let raw_value = line[eq + 1..].trim();
    let value = if raw_value.starts_with('"') && raw_value.ends_with('"') && raw_value.len() >= 2 {
        raw_value[1..raw_value.len() - 1].to_string()
    } else {
        raw_value.to_string()
    };
    Some((key, value))
}
