#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
#
# Generate dca/src/dcadec/tables.rs from ffmpeg's vendored DCA reference
# sources (read-only). Extracts only the tables the DTS *core* decoder needs
# (dcadata.c) plus the VLC source pairs (dcahuff.c). Re-run after a vendor
# bump; the output is committed.
#
# Usage:
#   python3 dca/scripts/gen_tables.py \
#       [<reference-sources>/ffmpeg_sources/libavcodec] \
#       [dca/src/dcadec/tables.rs]

import re
import sys
from pathlib import Path

DEFAULT_SRC = Path(
    "/home/user/dev/spatial-renderer/reference-sources/ffmpeg_sources/libavcodec"
)


def strip_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    text = re.sub(r"//[^\n]*", "", text)
    return text


def extract_body(text: str, name: str) -> str:
    """Return the brace-balanced initializer body for the named C array."""
    idx = text.find(name)
    if idx < 0:
        raise KeyError(name)
    eq = text.index("=", idx)
    start = text.index("{", eq)
    depth = 0
    i = start
    while i < len(text):
        c = text[i]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return text[start : i + 1]
        i += 1
    raise ValueError(f"unbalanced braces for {name}")


def to_rust_literal(body: str) -> str:
    # dcadata.c wraps some float tables in SCALE(c) = (c) / (256.0f * 32768.0f).
    # 256*32768 = 8388608 is exact in f32, so this expansion is bit-identical.
    body = re.sub(r"SCALE\(([^)]*)\)", r"(\1 / 8388608.0)", body)
    body = body.replace("{", "[").replace("}", "]")
    body = body.replace("+", "")  # drop unary plus (illegal in Rust literals)
    body = re.sub(r"[ \t]+", " ", body)
    return body.strip()


# (rust_name, c_name, rust_type) — fixed-size arrays from dcadata.c
DATA_TABLES = [
    ("BIT_RATES", "ff_dca_bit_rates", "[u32; 32]"),
    ("CHANNELS", "ff_dca_channels", "[u8; 16]"),
    ("QUANT_INDEX_SEL_NBITS", "ff_dca_quant_index_sel_nbits", "[u8; 10]"),
    ("QUANT_INDEX_GROUP_SIZE", "ff_dca_quant_index_group_size", "[u8; 10]"),
    ("SCALE_FACTOR_QUANT6", "ff_dca_scale_factor_quant6", "[u32; 64]"),
    ("SCALE_FACTOR_QUANT7", "ff_dca_scale_factor_quant7", "[u32; 128]"),
    ("JOINT_SCALE_FACTORS", "ff_dca_joint_scale_factors", "[u32; 129]"),
    ("SCALE_FACTOR_ADJ", "ff_dca_scale_factor_adj", "[u32; 4]"),
    ("QUANT_LEVELS", "ff_dca_quant_levels", "[u32; 32]"),
    ("LOSSY_QUANT", "ff_dca_lossy_quant", "[u32; 32]"),
    ("LOSSLESS_QUANT", "ff_dca_lossless_quant", "[u32; 32]"),
    ("HIGH_FREQ_VQ", "ff_dca_high_freq_vq", "[[i8; 32]; 1024]"),
    # Fixed-point synthesis path (self-contained, no av_tx IMDCT dependency).
    ("FIR_32BANDS_PERFECT_FIXED", "ff_dca_fir_32bands_perfect_fixed", "[i32; 512]"),
    ("FIR_32BANDS_NONPERFECT_FIXED", "ff_dca_fir_32bands_nonperfect_fixed", "[i32; 512]"),
    ("LFE_FIR_64_FIXED", "ff_dca_lfe_fir_64_fixed", "[i32; 256]"),
    ("LFE_FIR_64_FLOAT", "ff_dca_lfe_fir_64", "[f32; 256]"),
    ("ADPCM_VB", "ff_dca_adpcm_vb", "[[i16; 4]; 4096]"),
    # XLL (DTS-HD MA lossless) + downmix tables.
    ("DMIX_PRIMARY_NCH", "ff_dca_dmix_primary_nch", "[u8; 8]"),
    ("DMIXTABLE", "ff_dca_dmixtable", "[u16; 242]"),
    ("INV_DMIXTABLE", "ff_dca_inv_dmixtable", "[u32; 201]"),
    ("XLL_REFL_COEFF", "ff_dca_xll_refl_coeff", "[u16; 128]"),
    ("XLL_BAND_COEFF", "ff_dca_xll_band_coeff", "[i32; 20]"),
]

# Huffman metadata from dcahuff.c
HUFF_TABLES = [
    ("BITALLOC_SIZES", "ff_dca_bitalloc_sizes", "[u8; 10]"),
    ("BITALLOC_OFFSETS", "ff_dca_bitalloc_offsets", "[i8; 10]"),
]


def main() -> None:
    src_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_SRC
    out_path = (
        Path(sys.argv[2])
        if len(sys.argv) > 2
        else Path(__file__).resolve().parent.parent / "src" / "dcadec" / "tables.rs"
    )

    dcadata = strip_comments((src_dir / "dcadata.c").read_text())
    dcahuff = strip_comments((src_dir / "dcahuff.c").read_text())

    out = []
    out.append("// SPDX-License-Identifier: Apache-2.0")
    out.append("//")
    out.append("// GENERATED by dca/scripts/gen_tables.py from ffmpeg's vendored DCA")
    out.append("// reference sources. Do not edit by hand; re-run the generator.")
    out.append("#![allow(clippy::all)]")
    out.append("#![allow(dead_code)]")
    out.append("")

    for rust_name, c_name, rust_type in DATA_TABLES:
        body = to_rust_literal(extract_body(dcadata, c_name))
        out.append(f"pub static {rust_name}: {rust_type} = {body};")
        out.append("")

    for rust_name, c_name, rust_type in HUFF_TABLES:
        body = to_rust_literal(extract_body(dcahuff, c_name))
        out.append(f"pub static {rust_name}: {rust_type} = {body};")
        out.append("")

    # ff_dca_vlc_src_tables[][2] — flat slice of {symbol, length} pairs, in the
    # exact order ff_dca_init_vlcs() consumes them.
    body = to_rust_literal(extract_body(dcahuff, "ff_dca_vlc_src_tables"))
    out.append("/// `{symbol, length}` pairs, consumed in ff_dca_init_vlcs order.")
    out.append(f"pub static VLC_SRC_TABLES: &[[u8; 2]] = &{body};")
    out.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(out))
    print(f"wrote {out_path} ({out_path.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
